language: ruby
sudo: false
before_install: gem install bundler
gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
matrix:
  exclude:
    # NOTE : incompatible
    - rvm: 1.9.3
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.2.5
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/rails_32.gemfile
install: bundle install -j4 --path vendor/bundle
notifications:
    slack: evilmartians:3TVEqLTmDrMKUZZqUIy9apFT
